# Generated by Django 5.2.7 on 2025-10-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="contract_details",
            field=models.TextField(blank=True, verbose_name="مفاد قرارداد"),
        ),
    ]
