# Generated by Django 5.2.7 on 2025-10-23 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_booking_contract_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalonImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="salon_images/", verbose_name="تصویر"),
                ),
                (
                    "is_cover",
                    models.BooleanField(default=False, verbose_name="تصویر کاور"),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="booking.salon",
                        verbose_name="سالن",
                    ),
                ),
            ],
        ),
    ]
